
name: Perl Syntax Check

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Perl version
        run: perl -v


      - name: Install Perl modules
        run: sudo apt-get update && sudo apt-get install -y libdbi-perl libdbd-sqlite3-perl

      - name: Syntax check CGI
        run: |
          set -ex
          echo "Checking index.cgi"
          perl -c index.cgi

      - name: Syntax check modules
        run: |
          set -ex
          for f in $(find . -name '*.pm'); do
            echo "Checking $f"
            perl -c "$f"
          done
          echo "All done"

